import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-body flex flex-col min-h-screen bg-primary`}
      >
        <Header />
        <main className="flex-1 bg-background text-text flex flex-col">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
